### ISSUE TITLE
Virtual Environment

### ISSUE THREAD

**Issue by mlhale7** [DLFMetadataAssessment/DLFMetadataQAWorkshop17#14]
I'm having some trouble setting up a virtual environment and was hoping for some suggestions. I've attached the error message I'm getting in terminal. I know this is not absolutely required for the workshop, but I'd like to get it set up if I can. Thanks for your help!
[virtualenvError.txt](https://github.com/DLFMetadataAssessment/DLFMetadataQAWorkshop17/files/1416731/virtualenvError.txt)

**Comment by annie12345666** [comment]
I had this issue too, with pretty much the same error. I had to install pip, too...I'm on a Mac, running Sierra OS 10.12.6, for what it's worth. :-)

**Comment by cmharlow** [comment]
Are you able to run a `sudo` command on your machine? i.e. `sudo pip install virtualenv` (it'll ask for your password).

The error is your shell user does not have write permissions to where your Python install wants to put packages, fwiw.

**Comment by mlhale7** [comment]
Thanks! All set to go.
